name: "[CI] SmsTwilio"
on:
  push:
    branches:
      - develop
      - main
      - release/*
      - feature/0.26/zip-code-voting
  pull_request:

env:
  CI: "true"
  CODECOV: "true"
  DECIDIM_MODULE: decidim-sms-twilio

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: ./.github/actions/module-rspec
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.DECIDIM_MODULE }}
